[[getting-started-whats-next]]
= Next Steps

include::partial$_attributes.adoc[]

Hopefully, this section provided some of the {project-full-name} basics and got you on your way
to writing your own applications. If you are a task-oriented type of developer, you might
want to jump over to https://spring.io and check out some
https://spring.io/guides/[getting started] guides that solve specific "`How do I do that
with Spring?`" problems. We also have {project-full-name}-specific
"`xref:howto.adoc[how-to]`" reference documentation.

Otherwise, the next logical step is to read xref:using.adoc[Using {project-full-name}]. If
you are really impatient, you could also jump ahead and read about
<<project-features.adoc#project-features, {project-full-name} features>>.

In addition, you can check out the following videos:

- "Consumer Driven Contracts and Your Microservice Architecture" by Olga Maciaszek-Sharma and Marcin Grzejszczak

video::pDkC_00hhvA[youtube,width=640,height=480]

- "Contract Tests in the Enterprise" by Marcin Grzejszczak

video::ZyHG-VOzPZg[youtube,width=640,height=480]

- "Why Contract Tests Matter?" by Marcin Grzejszczak

video::TvpkZu1e2Dc[youtube,start=6262,width=640,height=480]

You can find the default project samples at
https://github.com/spring-cloud-samples/spring-cloud-contract-samples[samples].
