#%RAML 1.0
title: MUA Flights API
baseUri: http://localhost:8081/

/mallory:
  description: a retrieve Mallory request a user with username 'username' and password 'password' exists
  get:
    headers:
      Content-Type:
        description: The API key needed to create a new job
    queryParameters:
      name:
        default: ron
      status:
        default: good
    body:
      application/json:
        example: |
          {"id": "123", "method": "create"}
    responses:
      200:
       headers:
         Content-Type:
           default: application/json
       body:
         application/json:
           example: |
             [[{
             "email": "rddtGwwWMEhnkAPEmsyE",
             "id": "eb0f8c17-c06a-479e-9204-14f7c95b63a6",
             "userName": "AJQrokEGPAVdOHprQpKP"
             }]]