releaser.maven.buildCommand: ./scripts/noIntegration.sh {{systemProps}}
releaser.maven.deployCommand: ./mvnw deploy -DskipTests -B -Pfast,deploy
releaser.gradle.gradlePropsSubstitution:
  verifierVersion: spring-cloud-contract
  bootVersion: spring-boot
