== Stub Runner for Messaging

WARNING: Feature available since 1.0.7

Stub Runner has the functionality to run the published stubs in memory. It can integrate with the following frameworks out of the box

- Spring Integration
- Spring Cloud Stream
- Apache Camel

It also provides points of entry to integrate with any other solution on the market.

=== DSL

The DSL for messaging looks a little bit different than the one that focuses on HTTP.

==== Output triggered by a method

The output message can be triggered by calling a method (e.g. a Scheduler was started and a message was sent)

[source,groovy]
----
include::../../../../samples/messaging-integration/src/test/groovy/io/codearte/accurest/samples/messaging/IntegrationMessagingApplicationSpec.groovy[tags=method_trigger,indent=0]
----

In this case the output message will be sent to `output` if a method called `bookReturnedTriggered` will be executed. In the message *publisher's* side
we will generate a test that will call that method to trigger the message. On the *consumer* side you can use the `some_label` to trigger the message.

==== Output triggered by a message

The output message can be triggered by receiving a message.

[source,groovy]
----
include::../../../../samples/messaging-integration/src/test/groovy/io/codearte/accurest/samples/messaging/IntegrationMessagingApplicationSpec.groovy[tags=message_trigger,indent=0]
----

In this case the output message will be sent to `output` if a proper message will be received on the `input` destination. In the message *publisher's* side
we will generate a test that will send the input message to the defined destination. On the *consumer* side you can either send a message to the input
destination or use the `some_label` to trigger the message.

=== Stub triggering

To trigger a message it's enough to use the `StubTiggerer` interface:

[source,groovy]
----
include::../../../../stub-runner/stub-runner/src/main/groovy/io/codearte/accurest/stubrunner/StubTriggerer.groovy[]
----

For convenience the `StubFinder` interface extends `StubTrigger` so it's enough to use only one in your tests.

`StubTrigger` gives you the following options to trigger a message:

==== Trigger by label

[source,groovy]
----
include::../../../../stub-runner/stub-runner-messaging/stub-runner-messaging-camel/src/test/groovy/io/codearte/accurest/stubrunner/messaging/camel/CamelStubRunnerSpec.groovy[tags=client_trigger,indent=0]
----

===== Trigger by group and artifact ids

[source,groovy]
----
include::../../../../stub-runner/stub-runner-messaging/stub-runner-messaging-camel/src/test/groovy/io/codearte/accurest/stubrunner/messaging/camel/CamelStubRunnerSpec.groovy[tags=trigger_group_artifact,indent=0]
----

===== Trigger by artifact ids

[source,groovy]
----
include::../../../../stub-runner/stub-runner-messaging/stub-runner-messaging-camel/src/test/groovy/io/codearte/accurest/stubrunner/messaging/camel/CamelStubRunnerSpec.groovy[tags=trigger_artifact,indent=0]
----

===== Trigger all messages

[source,groovy]
----
include::../../../../stub-runner/stub-runner-messaging/stub-runner-messaging-camel/src/test/groovy/io/codearte/accurest/stubrunner/messaging/camel/CamelStubRunnerSpec.groovy[tags=trigger_all,indent=0]
----

include::../../../../stub-runner/stub-runner-messaging/stub-runner-messaging-camel/README.adoc[]

include::../../../../stub-runner/stub-runner-messaging/stub-runner-messaging-integration/README.adoc[]

include::../../../../stub-runner/stub-runner-messaging/stub-runner-messaging-stream/README.adoc[]