== Stub Runner

One of the issues that you could have encountered while using Accurest was to pass the generated WireMock JSON stubs from the server side to the client side (or various clients).
 The same takes place in terms of client side generation for messaging.

Copying the JSON files / setting the client side for messaging manually is out of the question.

=== Publishing stubs as JARs

The easiest approach would be to centralize the way stubs are kept. For example you can keep them as JARs in a Maven repository.

==== Gradle

Example of Accurest Gradle setup:

[source,groovy,indent=0]
----
include::../../../../accurest-gradle-plugin/src/test/resources/functionalTest/scenarioProject/build.gradle[tags=jar_setup,indent=0]
----

==== Maven

Example of Maven can be found in the https://github.com/Codearte/accurest-maven-plugin/=publishing-wiremock-stubs-projectf-stubsjar[Accurest Maven Plugin README]

=== Modules

Accurest comes with a new structure of modules

[source,indent=0]
----
└── stub-runner
    ├── stub-runner
    ├── stub-runner-boot
    ├── stub-runner-junit
    ├── stub-runner-spring
    └── stub-runner-spring-cloud
----

include::../../../../stub-runner/stub-runner/README.adoc[]
include::../../../../stub-runner/stub-runner-boot/README.adoc[]
include::../../../../stub-runner/stub-runner-junit/README.adoc[]
include::../../../../stub-runner/stub-runner-spring/README.adoc[]
include::../../../../stub-runner/stub-runner-spring-cloud/README.adoc[]


=== Common properties for JUnit and Spring

Some of the properties that are repetitive can be set using system properties or property sources (for Spring). Here are their names with their default values:

[width="60%",frame="topbot",options="header"]
|======================
| Property name | Default value | Description |
|stubrunner.port.range.min|10000| Minimal value of a port for a started WireMock with stubs|
|stubrunner.port.range.max|15000| Minimal value of a port for a started WireMock with stubs|
|stubrunner.stubs.repository.root|| Maven repo url. If blank then will call the local maven repo|
|stubrunner.stubs.classifier|stubs| Default classifier for the stub artifacts|
|stubrunner.work-offline|false| If true then will not contact any remote repositories to download stubs|
|stubrunner.stubs|| Comma separated list of Ivy notation of stubs to download|
|======================