[[contract-documentation]]
= Spring Cloud Contract Documentation
include::attributes.adoc[]

This section provides a brief overview of Spring Cloud Contract reference documentation. It serves
as a map for the rest of the document.



[[contract-documentation-about]]
== About the Documentation
The Spring Cloud Contract reference guide is available as

* {spring-cloud-contract-docs}/html[Multi-page HTML]
* {spring-cloud-contract-docs}/htmlsingle[Single page HTML]
* {spring-cloud-contract-docs}/pdf/spring-cloud-contract-reference.pdf[PDF]

The latest copy is available at {spring-cloud-contract-docs-current}.

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.



[[contract-documentation-getting-help]]
== Getting Help
If you have trouble with Spring Cloud Contract, we would like to help.

* Try the <<howto.adoc#howto, How-to documents>>. They provide solutions to the most
common questions.
* Learn the Spring Cloud Contract basics. If you are
starting out with Spring Cloud Contract, try one of the https://spring.io/guides[guides].
* Ask a question. We monitor https://stackoverflow.com[stackoverflow.com] for questions
tagged with https://stackoverflow.com/tags/spring-cloud-contract[`spring-cloud-contract`].
* Report bugs with Spring Cloud Contract at https://github.com/spring-cloud/spring-cloud-contract/issues.

NOTE: All of Spring Cloud Contract is open source, including the documentation. If you find
problems with the docs or if you want to improve them, please {github-code}[get
involved].



[[contract-documentation-first-steps]]
== First Steps
If you are getting started with Spring Cloud Contract or 'Spring' in general, start with
<<getting-started.adoc#getting-started, the following topics>>:

* *From scratch:*
<<getting-started.adoc#getting-started-introducing-spring-cloud-contract, Overview>> |
<<getting-started.adoc#getting-started-system-requirements, Requirements>> |
<<getting-started.adoc#getting-started-installing-spring-cloud-contract, Installation>>
* *Tutorial:*
<<getting-started.adoc#getting-started-first-application, Part 1>> |
<<getting-started.adoc#getting-started-first-application-code, Part 2>>
* *Running your example:*
<<getting-started.adoc#getting-started-first-application-run, Part 1>> |
<<getting-started.adoc#getting-started-first-application-executable-jar, Part 2>>



== Working with Spring Cloud Contract
Ready to actually start using Spring Cloud Contract? <<using-spring-cloud-contract.adoc#using-boot, We have
you covered>>:

* *Build systems:*
<<using-spring-cloud-contract.adoc#using-contract-maven, Maven>> |
<<using-spring-cloud-contract.adoc#using-contract-gradle, Gradle>> |
<<using-spring-cloud-contract.adoc#using-contract-ant, Ant>> |
<<using-spring-cloud-contract.adoc#using-contract-starter, Starters>>
* *Best practices:*
<<using-spring-cloud-contract.adoc#using-contract-structuring-your-code, Code Structure>> |
<<using-spring-cloud-contract.adoc#using-contract-configuration-classes, @Configuration>> |
<<using-spring-cloud-contract.adoc#using-contract-auto-configuration, @EnableAutoConfiguration>> |
<<using-spring-cloud-contract.adoc#using-contract-spring-beans-and-dependency-injection, Beans and
Dependency Injection>>
* *Running your code:*
<<using-spring-cloud-contract.adoc#using-contract-running-from-an-ide, IDE>> |
<<using-spring-cloud-contract.adoc#using-contract-running-as-a-packaged-application, Packaged>> |
<<using-spring-cloud-contract.adoc#using-contract-running-with-the-maven-plugin, Maven>> |
<<using-spring-cloud-contract.adoc#using-contract-running-with-the-gradle-plugin, Gradle>>
* *Packaging your app:*
<<using-spring-cloud-contract.adoc#using-contract-packaging-for-production, Production jars>>
* *Spring Cloud Contract CLI:*
<<spring-cloud-contract-cli.adoc#cli, Using the CLI>>



== Learning about Spring Cloud Contract Features
Need more details about Spring Cloud Contract's core features?
<<spring-cloud-contract-features.adoc#contract-features, The following content is for you>>:

* *Core Features:*
<<spring-cloud-contract-features.adoc#contract-features-spring-application, SpringApplication>> |
<<spring-cloud-contract-features.adoc#contract-features-external-config, External Configuration>> |
<<spring-cloud-contract-features.adoc#contract-features-profiles, Profiles>> |
<<spring-cloud-contract-features.adoc#contract-features-logging, Logging>>
* *Web Applications:*
<<spring-cloud-contract-features.adoc#contract-features-spring-mvc, MVC>> |
<<spring-cloud-contract-features.adoc#contract-features-embedded-container, Embedded Containers>>
* *Working with data:*
<<spring-cloud-contract-features.adoc#contract-features-sql, SQL>> |
<<spring-cloud-contract-features.adoc#contract-features-nosql, NO-SQL>>
* *Messaging:*
<<spring-cloud-contract-features.adoc#contract-features-messaging, Overview>> |
<<spring-cloud-contract-features.adoc#contract-features-jms, JMS>>
* *Testing:*
<<spring-cloud-contract-features.adoc#contract-features-testing, Overview>> |
<<spring-cloud-contract-features.adoc#contract-features-testing-spring-cloud-contract-applications, Boot
Applications>> |
<<spring-cloud-contract-features.adoc#contract-features-test-utilities, Utils>>
* *Extending:*
<<spring-cloud-contract-features.adoc#contract-features-developing-auto-configuration, Auto-configuration>> |
<<spring-cloud-contract-features.adoc#contract-features-condition-annotations, @Conditions>>



== Moving to Production
When you are ready to push your Spring Cloud Contract application to production, we have
<<production-ready-features.adoc#production-ready, some tricks>> that you might like:

* *Management endpoints:*
<<production-ready-features.adoc#production-ready-endpoints, Overview>> |
<<production-ready-features.adoc#production-ready-customizing-endpoints, Customization>>
* *Connection options:*
<<production-ready-features.adoc#production-ready-monitoring, HTTP>> |
<<production-ready-features.adoc#production-ready-jmx, JMX>>
* *Monitoring:*
<<production-ready-features.adoc#production-ready-metrics, Metrics>> |
<<production-ready-features.adoc#production-ready-auditing, Auditing>> |
<<production-ready-features.adoc#production-ready-tracing, Tracing>> |
<<production-ready-features.adoc#production-ready-process-monitoring, Process>>



== Advanced Topics
Finally, we have a few topics for more advanced users:

* *Spring Cloud Contract Applications Deployment:*
<<deployment.adoc#cloud-deployment, Cloud Deployment>> |
<<deployment.adoc#deployment-service, OS Service>>
* *Build tool plugins:*
<<build-tool-plugins.adoc#build-tool-plugins-maven-plugin, Maven>> |
<<build-tool-plugins.adoc#build-tool-plugins-gradle-plugin, Gradle>>
* *Appendix:*
<<appendix.adoc#common-application-properties, Application Properties>> |
<<appendix.adoc#auto-configuration-classes, Auto-configuration classes>> |
<<appendix.adoc#executable-jar, Executable Jars>>

