[[documentation]]
= Spring Cloud Contract Documentation
include::_attributes.adoc[]

This section provides a brief overview of {project-full-name} reference documentation. It serves
as a map for the rest of the document.



[[contract-documentation-about]]
== About the Documentation
The {project-full-name} reference guide is available as

* {docs-url}/html[Multi-page HTML]
* {docs-url}/htmlsingle[Single page HTML]
* {docs-url}/pdf/{project-name}.pdf[PDF]

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.



[[documentation-getting-help]]
== Getting Help
If you have trouble with {project-full-name}, we would like to help.

* Try the <<howto.adoc#howto, How-to documents>>. They provide solutions to the most
common questions.
* Learn the {project-full-name} basics. If you are
starting out with {project-full-name}, try one of the https://spring.io/guides[guides].
* Ask a question. We monitor https://stackoverflow.com[stackoverflow.com] for questions
tagged with https://stackoverflow.com/tags/{project-name}[`{project-name}`].
* Report bugs with {project-full-name} at https://github.com/spring-cloud/{project-name}/issues.

NOTE: All of {project-full-name} is open source, including the documentation. If you find
problems with the docs or if you want to improve them, please {github-code}[get
involved].



[[contract-documentation-first-steps]]
== First Steps
If you are getting started with {project-full-name} or 'Spring' in general, start with
<<getting-started.adoc#getting-started, the following topics>>:

* *From scratch:*
<<getting-started.adoc#getting-started-introducing-{project-name}, Overview>> |
<<getting-started.adoc#getting-started-three-second-tour, Three-second Tour>> |
<<getting-started.adoc#getting-started-first-application, First application>>
* *Tutorial:*
<<getting-started.adoc#getting-started-cdc, Introduction>> |
<<getting-started.adoc#consumer-side-loan-issuance, Consumer >> |
<<getting-started.adoc#producer-side-fraud-detection-server, Producer Part 1>> |
<<getting-started.adoc#consumer-side-loan-issuance-final-step, Consumer Part 2>>



== Working with {project-full-name}
Ready to actually start using {project-full-name}? <<using.adoc#using, We have
you covered>>:

* *Build systems:*
<<using-{project-name}.adoc#using-contract-maven, Maven>> |
<<using-{project-name}.adoc#using-contract-gradle, Gradle>> |
<<using-{project-name}.adoc#using-contract-ant, Ant>> |
<<using-{project-name}.adoc#using-contract-starter, Starters>>
* *Best practices:*
<<using-{project-name}.adoc#using-contract-structuring-your-code, Code Structure>> |
<<using-{project-name}.adoc#using-contract-configuration-classes, @Configuration>> |
<<using-{project-name}.adoc#using-contract-auto-configuration, @EnableAutoConfiguration>> |
<<using-{project-name}.adoc#using-contract-spring-beans-and-dependency-injection, Beans and
Dependency Injection>>
* *Running your code:*
<<using-{project-name}.adoc#using-contract-running-from-an-ide, IDE>> |
<<using-{project-name}.adoc#using-contract-running-as-a-packaged-application, Packaged>> |
<<using-{project-name}.adoc#using-contract-running-with-the-maven-plugin, Maven>> |
<<using-{project-name}.adoc#using-contract-running-with-the-gradle-plugin, Gradle>>
* *Packaging your app:*
<<using-{project-name}.adoc#using-contract-packaging-for-production, Production jars>>
* *{project-full-name} CLI:*
<<{project-name}-cli.adoc#cli, Using the CLI>>



== Learning about {project-full-name} Features
Need more details about {project-full-name}'s core features?
<<{project-name}-features.adoc#contract-features, The following content is for you>>:

* *Core Features:*
<<{project-name}-features.adoc#contract-features-spring-application, SpringApplication>> |
<<{project-name}-features.adoc#contract-features-external-config, External Configuration>> |
<<{project-name}-features.adoc#contract-features-profiles, Profiles>> |
<<{project-name}-features.adoc#contract-features-logging, Logging>>
* *Web Applications:*
<<{project-name}-features.adoc#contract-features-spring-mvc, MVC>> |
<<{project-name}-features.adoc#contract-features-embedded-container, Embedded Containers>>
* *Working with data:*
<<{project-name}-features.adoc#contract-features-sql, SQL>> |
<<{project-name}-features.adoc#contract-features-nosql, NO-SQL>>
* *Messaging:*
<<{project-name}-features.adoc#contract-features-messaging, Overview>> |
<<{project-name}-features.adoc#contract-features-jms, JMS>>
* *Testing:*
<<{project-name}-features.adoc#contract-features-testing, Overview>> |
<<{project-name}-features.adoc#contract-features-testing-{project-name}-applications, Boot
Applications>> |
<<{project-name}-features.adoc#contract-features-test-utilities, Utils>>
* *Extending:*
<<{project-name}-features.adoc#contract-features-developing-auto-configuration, Auto-configuration>> |
<<{project-name}-features.adoc#contract-features-condition-annotations, @Conditions>>



== Moving to Production
When you are ready to push your {project-full-name} application to production, we have
<<production-ready-features.adoc#production-ready, some tricks>> that you might like:

* *Management endpoints:*
<<production-ready-features.adoc#production-ready-endpoints, Overview>> |
<<production-ready-features.adoc#production-ready-customizing-endpoints, Customization>>
* *Connection options:*
<<production-ready-features.adoc#production-ready-monitoring, HTTP>> |
<<production-ready-features.adoc#production-ready-jmx, JMX>>
* *Monitoring:*
<<production-ready-features.adoc#production-ready-metrics, Metrics>> |
<<production-ready-features.adoc#production-ready-auditing, Auditing>> |
<<production-ready-features.adoc#production-ready-tracing, Tracing>> |
<<production-ready-features.adoc#production-ready-process-monitoring, Process>>



== Advanced Topics
Finally, we have a few topics for more advanced users:

* *{project-full-name} Applications Deployment:*
<<deployment.adoc#cloud-deployment, Cloud Deployment>> |
<<deployment.adoc#deployment-service, OS Service>>
* *Build tool plugins:*
<<build-tool-plugins.adoc#build-tool-plugins-maven-plugin, Maven>> |
<<build-tool-plugins.adoc#build-tool-plugins-gradle-plugin, Gradle>>
* *Appendix:*
<<appendix.adoc#common-application-properties, Application Properties>> |
<<appendix.adoc#auto-configuration-classes, Auto-configuration classes>> |
<<appendix.adoc#executable-jar, Executable Jars>>

