:branch: master
image::https://badges.gitter.im/Join%20Chat.svg[Gitter, link="https://gitter.im/spring-cloud/spring-cloud-contract?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
image::https://codecov.io/gh/spring-cloud/spring-cloud-contract/branch/{branch}/graph/badge.svg["codecov", link="https://codecov.io/gh/spring-cloud/spring-cloud-contract"]
image::https://circleci.com/gh/spring-cloud/spring-cloud-contract.svg?style=svg["CircleCI", link="https://circleci.com/gh/spring-cloud/spring-cloud-contract"]
:introduction_url: ../../../..

== Spring Cloud Contract

What you always need is confidence in pushing new features into a new application or service in a distributed system.
This project provides support for Consumer Driven Contracts and service schemas in Spring applications, covering a
range of options for writing tests, publishing them as assets, asserting that a contract is kept by producers
and consumers, for HTTP and message-based interactions.

=== Spring Cloud Contract workshops

If you prefer to learn about the project by doing some tutorials you can check out the workshops under
http://cloud-samples.spring.io/spring-cloud-contract-samples/workshops.html[this link].

=== Spring Cloud Contract Verifier

include::verifier_introduction.adoc[]

include::links.adoc[]

=== Spring Cloud Contract WireMock

include::spring-cloud-wiremock.adoc[]

== Documentation

You can read more about Spring Cloud Contract Verifier by reading the {documentation_url}[docs]

== Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]

include::building.adoc[]
