== Stub Runner for Messaging

Stub Runner can run the published stubs in memory. It can integrate with the following
frameworks:

* Spring Integration
* Spring Cloud Stream
* Spring AMQP

It also provides entry points to integrate with any other solution on the market.

IMPORTANT: If you have multiple frameworks on the classpath Stub Runner will need to
define which one should be used. Let's assume that you have both AMQP, Spring Cloud Stream and Spring Integration
on the classpath. Then you need to set `stubrunner.stream.enabled=false` and `stubrunner.integration.enabled=false`.
That way the only remaining framework is Spring AMQP.

=== Stub triggering

To trigger a message, use the `StubTrigger` interface:

[source,groovy]
----
include::{stubrunner_core_path}/src/main/java/org/springframework/cloud/contract/stubrunner/StubTrigger.java[lines=16..-1]
----

For convenience, the `StubFinder` interface extends `StubTrigger`, so you only need one
or the other in your tests.

`StubTrigger` gives you the following options to trigger a message:

* <<trigger-label>>
* <<trigger-group-artifact-ids>>
* <<trigger-artifact-ids>>
* <<trigger-all-messages>>

[[trigger-label]]
==== Trigger by Label

[source,groovy]
----
include::{tests_path}/spring-cloud-contract-stub-runner-stream/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/stream/StreamStubRunnerSpec.groovy[tags=client_trigger,indent=0]
----
[[trigger-group-artifact-ids]]
==== Trigger by Group and Artifact Ids

[source,groovy]
----
include::{tests_path}/spring-cloud-contract-stub-runner-stream/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/stream/StreamStubRunnerSpec.groovy[tags=trigger_group_artifact,indent=0]
----

[[trigger-artifact-ids]]
==== Trigger by Artifact Ids

[source,groovy]
----
include::{tests_path}/spring-cloud-contract-stub-runner-stream/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/stream/StreamStubRunnerSpec.groovy[tags=trigger_artifact,indent=0]
----

[[trigger-all-messages]]
==== Trigger All Messages

[source,groovy]
----
include::{tests_path}/spring-cloud-contract-stub-runner-stream/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/stream/StreamStubRunnerSpec.groovy[tags=trigger_all,indent=0]
----

include::{tests_path}/spring-cloud-contract-stub-runner-integration/README.adoc[]

include::{tests_path}/spring-cloud-contract-stub-runner-stream/README.adoc[]

include::{tests_path}/spring-cloud-contract-stub-runner-amqp/README.adoc[]
